// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCysWpxRD-XJnYlo9U_k5HlpbDA2c_kLM0',
    appId: '1:119726736438:web:a3860a7861fd3de6120497',
    messagingSenderId: '119726736438',
    projectId: 'chatly-2d563',
    authDomain: 'chatly-2d563.firebaseapp.com',
    storageBucket: 'chatly-2d563.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDz0p1chUhxJkXusSWxbP26HBtaXH8vbQ',
    appId: '1:119726736438:android:df47054f16b319a8120497',
    messagingSenderId: '119726736438',
    projectId: 'chatly-2d563',
    storageBucket: 'chatly-2d563.firebasestorage.app',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCysWpxRD-XJnYlo9U_k5HlpbDA2c_kLM0',
    appId: '1:119726736438:web:b1cba08f058dd467120497',
    messagingSenderId: '119726736438',
    projectId: 'chatly-2d563',
    authDomain: 'chatly-2d563.firebaseapp.com',
    storageBucket: 'chatly-2d563.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0VUzXt9-bsgfn8gLCOJQn65qpKdyJ26E',
    appId: '1:119726736438:ios:de4f1eb6d3dab8fb120497',
    messagingSenderId: '119726736438',
    projectId: 'chatly-2d563',
    storageBucket: 'chatly-2d563.firebasestorage.app',
    iosBundleId: 'com.chat.chatly',
  );
}
